# Image for Github Actions workflows to build and deploy the front-end image
FROM node:latest AS build-stage
WORKDIR /app
RUN git clone https://github.com/GPTStonks/front-end.git front-end
WORKDIR /app/front-end
RUN npm install --force && \
    npm run build

FROM nginx:alpine
COPY --from=build-stage /app/front-end/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
